adminClient:
    pattern:  /
    defaults: { _controller: "EcommerceBundle:ClientAdmin:index" }

adminClient_new:
    pattern:  /new
    defaults: { _controller: "EcommerceBundle:ClientAdmin:newMedia" }

adminClient_show:
     pattern:  /{id}/show
     defaults: { _controller: "EcommerceBundle:ClientAdmin:showMedia" }

adminClient_create:
    pattern:  /create
    defaults: { _controller: "EcommerceBundle:ClientAdmin:create" }
    requirements: { _method: post }

adminClient_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "EcommerceBundle:ClientAdmin:edit" }
adminClient_update:
    pattern:  /{id}/update
    defaults: { _controller: "EcommerceBundle:ClientAdmin:update" }
    requirements: { _method: post|put }

adminClient_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "EcommerceBundle:ClientAdmin:delete" }
    requirements: { _method: post|delete }
