supprimer:
    pattern:  /supprimer/{id}
    defaults: { _controller: EcommerceBundle:Panier:supprimer }

ajouter:
    pattern:  /ajouter/{id}
    defaults: { _controller: EcommerceBundle:Panier:ajouter }

valider:
    pattern:  /valider
    defaults: { _controller: EcommerceBundle:Panier:valider }

panier:
    pattern:  /
    defaults: { _controller: EcommerceBundle:Panier:panier }



